---
title: Error del compilador CS1017
ms.date: 07/20/2015
f1_keywords:
- CS1017
helpviewer_keywords:
- CS1017
ms.assetid: e0902e8a-b042-4711-a8a6-83456a3f88cb
ms.openlocfilehash: 03e4bbc41d0a103a1432906e77df4325f9a30e3f
ms.sourcegitcommit: 10986410e59ff29f2ec55c6759bde3eb4d1a00cb
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 05/31/2019
ms.locfileid: "66423133"
---
# <a name="compiler-error-cs1017"></a>Error del compilador CS1017
No puede haber cláusulas catch después de la cláusula catch general de una instrucción try  
  
 Un bloque `catch` que no tome ningún parámetro debe ser el último de una serie de `catch` bloques. Para obtener más información sobre excepciones, vea [excepciones y control de excepciones](../../csharp/programming-guide/exceptions/index.md).  
  
## <a name="example"></a>Ejemplo  
 El ejemplo siguiente genera la advertencia CS1017:  
  
```csharp  
// CS1017.cs  
using System;  
  
namespace x  
{  
    public class b : Exception  
    {  
    }  
  
    public class a  
    {  
        public static void Main()  
        {  
            try  
            {  
            }  
  
            catch   // CS1017, must be last catch  
            {  
            }  
  
            catch(b)  
            {  
                throw;  
            }  
        }  
    }  
}  
```
