---
title: Error del compilador CS1017
ms.date: 07/20/2015
f1_keywords:
- CS1017
helpviewer_keywords:
- CS1017
ms.assetid: e0902e8a-b042-4711-a8a6-83456a3f88cb
ms.openlocfilehash: 6371673d05ecd427dd410ea639f0f0671f851697
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/23/2019
ms.locfileid: "61654020"
---
# <a name="compiler-error-cs1017"></a>Error del compilador CS1017
No puede haber cláusulas catch después de la cláusula catch general de una instrucción try  
  
 Un bloque `catch` que no tome ningún parámetro debe ser el último de una serie de `catch` bloques. Para más información sobre excepciones, vea [Exception Handling Statements](../../csharp/language-reference/keywords/exception-handling-statements.md).  
  
## <a name="example"></a>Ejemplo  
 El ejemplo siguiente genera la advertencia CS1017:  
  
```csharp  
// CS1017.cs  
using System;  
  
namespace x  
{  
    public class b : Exception  
    {  
    }  
  
    public class a  
    {  
        public static void Main()  
        {  
            try  
            {  
            }  
  
            catch   // CS1017, must be last catch  
            {  
            }  
  
            catch(b)  
            {  
                throw;  
            }  
        }  
    }  
}  
```
